export const TUNING = {
  diagnostics: {
    enabled: false,
  },
  audioUpload: {
    maxFileBytes: 30 * 1024 * 1024,
    maxDurationSeconds: 600,
    allowedMimeTypes: [
      "audio/mpeg",
      "audio/mp3",
      "audio/wav",
      "audio/x-wav",
      "audio/ogg",
    ],
    allowedExtensions: ["mp3", "wav", "ogg"],
  },
  demo: {
    thresholdBase: 0.98,
    thresholdMid: 0.95,
    thresholdLate: 0.85,
    midPhaseStart: 300,
    latePhaseStart: 900,
    resetAfter: 1300,
    latePhaseWillowChance: 0.5,
  },
  audioAnalyzer: {
    analysisFps: 60,
    climaxRmsThreshold: 0.3,
    climaxFramesThreshold: 60,
    bass: {
      threshold: 0.4,
      thresholdClimax: 0.3,
      cooldown: 0.35,
      cooldownClimax: 0.2,
      launchRatioMin: 0.15,
      launchRatioMax: 0.3,
    },
    mid: {
      threshold: 0.15,
      cooldown: 0.15,
      launchRatioMin: 0.4,
      launchRatioMax: 0.6,
    },
    piano: {
      quietMin: 0.05,
      quietMax: 0.15,
      cooldown: 0.8,
      energyScale: 0.8,
      launchRatioMin: 0.3,
      launchRatioMax: 0.7,
    },
    waveformSamples: 1000,
    progressStep: 100,
  },
  beatDetector: {
    fps: 60,
    onsetWindowSeconds: 0.1,
    onsetThreshold: 0.15,
    onsetMinEnergy: 0.1,
    onsetMinDistance: 0.15,
    tempo: {
      fallbackBpm: 120,
      minInterval: 0.3,
      maxInterval: 1.0,
      histogramBin: 0.02,
      normalizeMinBpm: 80,
      normalizeMaxBpm: 160,
      confidenceDivisor: 0.5,
    },
    beatGrid: {
      offsetStep: 0.01,
      alignmentTolerance: 0.05,
    },
  },
  sectionDetector: {
    windowSize: 4,
    minSectionDuration: 8,
    trendThreshold: 0.1,
    highThresholdFactor: 0.5,
    lowThresholdFactor: 0.5,
    climaxCountThreshold: 2,
    climaxEnergyFactor: 0.95,
    chorusEnergyFactor: 0.7,
    chorusEventCount: 5,
    prechorusEnergyFactor: 0.8,
    lowEventCount: 2,
    introPosition: 0.15,
    outroPosition: 0.85,
    defaultEnergy: 0.5,
    transitionThreshold: 0.5,
  },
  ruleEngine: {
    finale: {
      cooldown: 10,
      remainingSeconds: 10,
      minEnergy: 0.6,
      targetY: 0.2,
    },
    climaxSalvo: {
      cooldown: 2,
      targetY: 0.2,
      countBase: 15,
      countEnergyScale: 10,
      intervalMs: 40,
    },
    beatDrop: {
      cooldown: 4,
      nearBeatTolerance: 0.1,
      recentEnergyWindow: 3,
      recentEnergyThreshold: 0.3,
      minEnergy: 0.6,
      targetY: 0.2,
      count: 5,
    },
    sectionTransition: {
      cooldown: 8,
      nearStartWindow: 0.5,
      targetY: 0.25,
    },
    chorusSymmetric: {
      cooldown: 1.5,
      minEnergy: 0.5,
      spread: 0.25,
    },
    pianoBeatSync: {
      cooldown: 0.3,
      beatTolerance: 0.05,
      minEnergy: 0.5,
      energyScale: 0.9,
      hue: 45,
    },
    bassImpact: {
      cooldown: 0.35,
      minEnergy: 0.4,
    },
    midAccent: {
      cooldown: 0.2,
      minEnergy: 0.3,
      energyScale: 0.8,
    },
    ambientScatter: {
      cooldown: 3,
      maxEnergy: 0.3,
      targetY: 0.4,
      count: 3,
      energy: 0.45,
    },
  },
  choreographer: {
    recentEventsWindow: 2,
    lookAheadSeconds: 0.5,
    launchTrackingWindow: 3,
    sparseThreshold: 3,
    minEnergyFloor: 0.55,
    sparseBoostPerMissing: 0.15,
    energyCap: 1.0,
    defaultTrigger: {
      targetYFactor: 0.25,
      energy: 0.6,
    },
  },
  timeline: {
    climaxCooldown: 2.0,
    initialSalvoTime: -10,
    climaxWillowRoll: 0.6,
  },
} as const;
